preparing script for fetching new esgf_ats_static.xml file

diff --git a/bin/esg-security b/bin/esg-security
--- a/bin/esg-security
+++ b/bin/esg-security
@@ -383,6 +383,29 @@ setup_policy_files() {
     fi
 }
 
+_fetch_static_ats_whitelist() {
+    local config_dir=${esg_config_dir}
+    local static_list_file="esgf_ats_static.xml"
+    if [ -d "${config_dir:-/esg/config}" ]; then
+        if [ -e "${config_dir}/${static_list_file}" ] && debug_print "${config_dir}/${static_list_file} is present will NOT fetch from distribution site" && return 0
+        checked_get ${config_dir}/${static_list_file} ${esg_dist_url}/lists/${static_list_file} $((force_install))
+        (( $? > 1 )) && echo debug_print "[DEBUG]: Could not fetch ${static_list_file} from distribution server" && return 1
+        chown -R ${tomcat_user}:${tomcat_group} ${config_dir}/${static_list_file}
+        chmod 644 ${config_dir}/${static_list_file}
+    fi
+    return 0
+}
+
+#--------------------------------------
+# Callout function from esg-node
+#--------------------------------------
+#This function is called by esg-node before starting tomcat!
+#This is how we make sure we are always using the proper credentials.
+security_startup_hook() {
+    echo -n "Security Startup Hook:... "
+    _fetch_static_ats_whitelist && echo "[OK]" || echo "[FAIL]"
+}
+
 #-------------------
 #Utility function, wraps md5sum so it may be used on either mac or
 #linux machines
