Can uninstall itself now... (esg-security)

diff --git a/bin/esg-security b/bin/esg-security
--- a/bin/esg-security
+++ b/bin/esg-security
@@ -67,6 +67,8 @@ envfile="/etc/esg.env"
 #User Defined / Setable (public)
 #--------------
 install_prefix=${install_prefix:-"/usr/local"}
+cdat_home=${cdat_home:-${install_prefix}/cdat}
+esg_root_dir=${esg_root_dir:-"/esg"}
 workdir=${workdir:-~/workbench/esg}
 install_logfile=${install_logfile:-"/etc/esg.install_log"}
 #--------------
@@ -85,8 +87,8 @@ init() {
     #[ -n "${envfile}" ] && [ -e "${envfile}" ] && source ${envfile} && ((VERBOSE)) && printf "security services: sourcing environment from: ${envfile} \n"
 
     security_dist_url=${esg_dist_url}/esgf-security/esgf-security.war
-    security_context_root=esgf-security
-    security_app_home=${tomcat_install_dir}/webapps/${security_context_root}
+    security_app_context_root=esgf-security
+    security_app_home=${tomcat_install_dir}/webapps/${security_app_context_root}
 
     esgf_security_version=${esgf_security_version:-"1.2.0"}
     esgf_security_db_version=${esgf_security_db_version:-"0.1.4"}
@@ -117,7 +119,7 @@ setup_security() {
     init
 
     echo -n "Checking for security services ${esgf_security_version}"
-    check_webapp_version "${security_context_root}" "${esgf_security_version}"
+    check_webapp_version "${security_app_context_root}" "${esgf_security_version}"
     local ret=$?
     ((ret == 0)) && (( ! force_install )) && echo " [OK]" && return 0
     
@@ -189,7 +191,7 @@ setup_security() {
 }
 
 write_security_install_log() {
-    echo "$(date ${date_format}) webapp:${security_context_root}=${esgf_security_version} ${security_app_home}" >> ${install_logfile}
+    echo "$(date ${date_format}) webapp:${security_app_context_root}=${esgf_security_version} ${security_app_home}" >> ${install_logfile}
     dedup ${install_logfile}
     return 0
 }
@@ -252,5 +254,54 @@ configure_postgress() {
 write_security_db_install_log() {
     echo "$(date ${date_format}) python:esgf_security=${esgf_security_db_version} " >> ${install_logfile}
     dedup ${install_logfile}
+    return 0
+}
+
+#--------------------------------------
+# Clean / Uninstall this module...
+#--------------------------------------
+
+clean_security_webapp_subsystem() {
+    init
+    local doit="N"
+    if [ -e ${security_app_home} ]; then
+        read -p "remove ESGF Security web service? (${security_app_home}) [y/N]: " doit
+        if [ "doit" = "Y" ] || [ "$doit" = "y" ]; then
+            echo "removing ${tomcat_install_dir}/webapps/${security_app_context_root}"
+            if [ -n ${security_app_home} ]; then
+                rm -rf ${security_app_home}
+                [ $? != 0 ] && echo "ERROR: Unable to remove ${tomcat_install_dir}/webapps/${security_app_context_root}" && return 1
+                perl -n -i -e'print unless m!webapp:esgf-security!' ${install_logfile}
+            fi
+        fi
+    fi 
+    return 0
+}
+
+#NOTE: There are certain fields that we are not pulling from (node_db_name and postgress_host).
+#      If the fit hits the shan I want to make it clear that we are not nuking anyone else's database, etc.
+#      strictly the "esgcet" database on "localhost"
+clean_security_database_subsystem_installation() {
+    init
+    local doit="N"
+
+    if $(psql -U ${postgress_user} esgcet -c "\dt esgf_security.;" | egrep '^\([1-9]* row[s]?\)' >& /dev/null); then
+        read -p "remove ESGF Security database, database subsystem AND DATA? (esgf_security.*) [y/N]: " doit
+
+        if [ "doit" = "Y" ] || [ "$doit" = "y" ]; then
+            #Call me paranoid but I want some integrity check that this code is what is meant to be straight from the distribution.
+            diff <(md5sum ${scripts_dir}/esg-security | tr -s " " | cut -d " " -f 1) <(curl -s -L --insecure ${esg_dist_url}/esgf-security/esg-security.md5 | tr -s " " | cut -d " " -f 1) >& /dev/null
+            [ $? != 0 ] && echo " WARNING: Could not verify ${scripts_dir}/esg-security, aborting this uninstall" && return 3
+            echo "[VERIFIED]"
+
+            backup_db esgcet security
+            echo "removing esgf_security.* schema and tables and DATA"
+            ${cdat_home}/bin/esgf_security_initialize --dburl ${postgress_user}:${pg_sys_acct_passwd}@localhost:${postgress_port}/esgcet -d 0
+            [ $? != 0 ] && echo "ERROR: Unable to remove ${tomcat_install_dir}/webapps/${security_app_context_root}" && return 1
+            rm -rvf ${cdat_home}/bin/esgf_security_initialize && \
+                rm -rf ${cdat_home}/lib/python${python_version}/${esgf_security_egg_file} && \
+                perl -n -i -e'print unless m!python:esgf_security!' ${install_logfile} && echo "[REMOVED]"
+        fi
+    fi 
     return 0
 }
